Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-053b0d53c279acc90
      Tags:
        - Key: "Name"
          Value: !Join
            - " "
            - - "My inst in"
              - !Ref AWS::Region
